config/routes.rb
Rails.application.routes.draw do
  resources :users
  # resources :user_messages
  resources :user_categories
  # resources :messages
  resources :friendships
  # resources :follows
  # resources :comments
  resources :categories
  resources :action_posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete "/sessions/logout", to: "sessions#logout", as: "logout"
  get "/sessions/new", to: "sessions#new", as: "new_login"
  post "/sessions", to: "sessions#create", as: "login"
  
  root 'welcome#home'
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :conversations, :foreign_key => :sender_id

    has_many :action_posts
    has_many :comments
    has_many :user_categories
    has_many :categories, through: :user_categories

    has_many :friendships
    has_many :friends, :through => :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user
    

    # has_many :messages, through: :user_messages

    # has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    # has_many :followees, through: :followed_users
    # has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    # has_many :followers, through: :following_users

    # has_many :sending_users, foreign_key: :sender_id, class_name: 'UserMessages'
    # has_many :receiver, through: :receiving_users
    # has_many :sending_users, foreign_key: :receiver_id, class_name: 'UserMessages'
    # has_many :sender, through: :sending_users

    def name
        "#{self.first_name} #{self.last_name}"
    end

    def self.all_except(user)
        where.not(id: user)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only:[:show, :edit, :update]

    def index
        @users = User.all
    
        @all_except_me = User.all_except(@current_user)
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)
        # # return redirect_to controller: 'users', action: 'new' unless @user.save
        # session[:user_id] = @user.id
        # redirect_to user_path(@user.id)

        if user.valid? 
            session[:user_id] = user.id
            redirect_to user_path(user.id)
           else
             flash[:user_errors] = user.errors.full_messages
       
             redirect_to new_user_path 
           end 
    end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to user_path(@user.id)
    end

    private
    
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :img_url, :img_token, :user_name)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<style>
.edit-profle {
  margin: 0% 10%

}
</style>
<div class=edit-profile>

<div class="css-input"><%= Edit Profile</div>
<br><br>

<%= form_for @user do |f| %>

<%= f.label :first_name %><br>
<%= f.text_field :first_name, :size=>"50" %><br><br>

<%= f.label :last_name %><br>
<%= f.text_field :last_name, :size=>"50" %><br><br>

<%= f.label :img_url %><br>
<%= f.text_field :img_url, :size=>"50" %><br><br>

<%= f.submit %>

<% end %>

</div>

app/views/users/home.html.erb
  
<h1>Hi there, <%= current_user.name %></h1>.

app/views/users/index.html.erb
<style>
.user-index {
  margin: 0% 10%

}
</style>
<div class=user-index>
<div class="css-input">Find a Friend</div>
<br><br><br>
<% if flash[:errors] %>
<% flash[:errors].each do |error| %>
<h3><%= error %></h3>
<% end %>
<% end %>

<div id="users">
<% @all_except_me.sort {|a,b| a.first_name <=> b.first_name}.each do |user| %>
  <%= user.name%>
      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
      <div class="clear"></div>

<% end %>
</div>

</div>

app/views/users/new.html.erb
<style>
.sign-up {
  margin: 0% 10%
}
</style>

<div class="sign-up">
<div class="css-input">Sign-up for TheNew</div>

<br><br><br>
</body>
<h4>
<%= form_for :user, url: '/users' do |f| %>
<%= f.label :first_name %><br>
<%= f.text_field :first_name, :size=>"50" %><br><br>

<%= f.label :last_name %><br>
<%= f.text_field :last_name, :size=>"50" %><br><br>

<%= f.label :user_name %><br>
<%= f.text_field :user_name, :size=>"50" %><br><br>

<%= f.label :email %><br>
<%= f.text_field :email, :size=>"50" %><br><br>

<%= f.label :img_url %><br>
<%= f.text_field :img_url, :size=>"50" %><br><br><br>

<%= f.label :password %><br>
<%= f.password_field :password, :size=>"50" %><br><br>

<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation, :size=>"50" %><br><br>



<%= f.submit %>

</h4>

<% end %>

<h4>Already a member? <%= link_to "Click here", new_login_path %> to go back to the login page.</h4>
</div>

app/views/users/show.html.erb
<style>
.user-show {
  margin: 0% 10%

}
</style>
<div class=user-show>
<% if @current_user.id == @user.id %>
<div class="css-input">Your Dashboard</div>
<% else %>
<div class="css-input"><%= @user.first_name.titleize %>'s Dashboard</div>
<% end %>
<br><br>
<img src= <%= @user.img_url %> alt="user_img" class="profile-image">

<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:10px">
<% if @current_user.id == @user.id %>
<h2>My Action Cards</h2>
<% else %>
<div><%= @user.first_name %>'s' Action Cards</div>
<% end %>
  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="post">
  <% @user.action_posts.sort {|a,b| b.id <=> a.id}.each do |post| %>
    <div class="w3-quarter">
    <div class="image-overlay-container">
      <img src= <%= post.img_url %> alt="post image" class="image" >
      <% if @current_user %>
      <div class="overlay"><%= link_to simple_format("#{post.title.titleize}\n#{post.category.tag.downcase}"), post%></div>
      <% else %>
      <div class="overlay"><%= link_to simple_format("#{post.title.titleize}\n#{post.category.tag.downcase}"), new_login_path%></div>
      <% end %>
    </div>
    </div>
  <% end %>
  
</div>




<% if @current_user.id == @user.id %>
<h2>My Friends</h2>
<% if @user.friendships.empty? %>
<p><%= link_to "Make a connection with a current user", users_path %> or 
<%= link_to "Pick an Action Card and send a friend request to the author", action_posts_path %></p>
<% else %>
<ul>
    <% @user.friendships.each do |friendship| %>
    <li>
      <%= friendship.friend.name %>
      <%= link_to 'Message me!', conversations_path(sender_id: @current_user.id, receiver_id: friendship.friend.id), method: 'post'%>
      (<%= link_to "remove", friendship, :method => :delete %>)
    
    </li>
  <% end %>
</ul>
<% end %>

<p><%= link_to "Edit Your Profile", edit_user_path(@current_user.id)  %> </p>

<% else %>
<h4><%= link_to "Click Here", friendships_path(:friend_id => @user), :method => :post %> to add <%= @user.first_name %> to your friend list.</h4>
      <div class="clear">
<% end %>

</div>