config/routes.rb
Rails.application.routes.draw do
  resources :users
  # resources :user_messages
  resources :user_categories
  # resources :messages
  resources :friendships
  # resources :follows
  # resources :comments
  resources :categories
  resources :action_posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete "/sessions/logout", to: "sessions#logout", as: "logout"
  get "/sessions/new", to: "sessions#new", as: "new_login"
  post "/sessions", to: "sessions#create", as: "login"
  
  root 'welcome#home'
  
end

app/models/action_post.rb
class ActionPost < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    has_many :messages
end

app/controllers/action_posts_controller.rb
class ActionPostsController < ApplicationController
    before_action :find_action_post, only:[:show, :edit, :update, :destroy]
    def index
        @action_posts = ActionPost.all
    end

    def show
        @comment = Comment.new
        @comment.action_post_id = @action_post.id
    end

    def new
        @action_post = ActionPost.new
        @categories = Category.all
    end

    def create
        action_post = ActionPost.new(action_post_params)
        action_post.user_id = session[:user_id]
        action_post.save

        redirect_to action_post_path(action_post.id)
    end

    def edit
    end

    def update
        @action_post.update(action_post_params)
        redirect_to action_post_path(@action_post.id)
    end

    def destroy
        @action_post.destroy
        redirect_to action_posts_path
    end

    private

    def action_post_params
        params.require(:action_post).permit(:title, :content, :location, :category_id, :img_url)
    end

    def find_action_post
        @action_post = ActionPost.find(params[:id])
    end
end

app/helpers/action_posts_helper.rb
module ActionPostsHelper
end

app/views/action_posts/_comment.html.erb
<div>
    <h4>comment by:<%= comment.user.name %></h4>
    <p class="comment"><%= comment.content %></p>
    <%= comment.created_at %>
  </div>

app/views/action_posts/edit.html.erb
<h1>edit posts</h1>
<%= form_for @action_post do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br><br>

<%= f.label :location %><br>
<%= f.text_field :location %><br><br>

<%= f.label :category_id %><br>
<%= f.collection_select :category_id, Category.all, :id, :name %><br><br>

<%= f.label :content %><br>
<%= f.text_area :content %><br><br>

<%= f.label :img_url %><br>
<%= f.text_field :img_url %><br><br>

<%= f.submit %><br>

<% end %>

app/views/action_posts/index.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid orange;
  padding: 10px;
  text-align: center;
}
.css-input {
     padding: 28px;
     font-size: 50px;
     border-width: 1px;
     border-color: #cccccc;
     background-color: #ffa500;
     color: #ffffff;
     border-style: dotted;
     border-radius: 27px;
     box-shadow: -4px 5px 7px rgba(66,66,66,.54);
     text-shadow: 0px 0px 5px rgba(66,66,66,.75);
     text-align: center;
     
}
 .css-input:focus {
     outline:none;
 }

 .ap-index {
  margin: 0% 3%

}
</style>

<div class="ap-index">
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:10px">
<div class="css-input">Do Something Amazing</div>
  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="post">
  <% @action_posts.sort {|a,b| b.id <=> a.id}.each do |post| %>
    <div class="w3-quarter">
    <div class="image-overlay-container">
      <img src= <%= post.img_url %> alt="post image" class="image" >
      <% if @current_user %>
      <div class="overlay"><%= link_to simple_format("#{post.title.titleize}\n#{post.category.tag.downcase}"), post%></div>
      <% else %>
      <div class="overlay"><%= link_to simple_format("#{post.title.titleize}\n#{post.category.tag.downcase}"), new_login_path%></div>
      <% end %>
    </div>
    </div>
  <% end %>
  
</div>

</div>

app/views/action_posts/new.html.erb
<h1>create new post</h1>
<%= form_for @action_post do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br><br>

<%= f.label :location %><br>
<%= f.text_field :location %><br><br>

<%= f.label :category_id %><br>
<%= f.collection_select :category_id, @categories, :id, :name %><br><br>

<%= f.label :content %><br>
<%= f.text_area :content %><br><br>

<%= f.label :img_url %><br>
<%= f.text_field :img_url %><br><br>



<%= f.submit %><br>

<% end %>

app/views/action_posts/show.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid orange;
  padding: 10px;
  text-align: center;
}
.css-input {
     padding: 28px;
     font-size: 50px;
     border-width: 1px;
     border-color: #cccccc;
     background-color: #ffa500;
     color: #ffffff;
     border-style: dotted;
     border-radius: 27px;
     box-shadow: -4px 5px 7px rgba(66,66,66,.54);
     text-shadow: 0px 0px 5px rgba(66,66,66,.75);
     text-align: center;
     
}
 .css-input:focus {
     outline:none;
 }

 .ap-show {
  margin: 0% 10%

}
</style>

<div class="ap-show">
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:10px">

<div class="css-input"><%= @action_post.title.titleize %></div>


<div>
<div class="image-overlay-container" id="show_img">
      <img src= <%= @action_post.img_url %> alt="post image" class="show-image" >
    </div>
    </div>
<div>Posted by <%= link_to @action_post.user.user_name.titleize, @action_post.user %></div><br><br>
<div class="location">Location: <%= @action_post.location.titleize %></div><br><br>
<div class="category">Action Category: <%= @action_post.category.name.titleize %>, <%= @action_post.category.tag.upcase %></div><br><br>
<p class="content"><%= @action_post.content %></p><br><br>


<% if @action_post.user.id != session[:user_id] %>
  <div></div>
<% else %>
<div><%= button_to "Edit Post", edit_action_post_path(@action_post), method: :get %></div>
<div><%= button_to 'Delete Post', action_post_path(@action_post), method: :delete %></div>
<%end %>
<br>
<div class="container-fluid" border-style="solid">
<h3>Comments</h3>	
<%= render partial: 'comments/form' %>	<br>
<%= render partial: 'action_posts/comment', collection: @action_post.comments.reverse %>
</div>



 
</div>

</div>